In [1]:
# import the packages
import numpy as np


In [3]:
#Write a program to create a vector with values ranging from 10  to 49

range_data = np.arange(10,49)
print(range_data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
# 2. Write a Python program to reverse a vector (first element becomes last)

import numpy as np

#initializing the numpy array
original_array = np.arange(1,10)
print('Orginal Array is  ',original_array)

#Reverse an array
print('Reverse an Array is  ',original_array[::-1])

#Another method to reverse the vector

reverse_array = np.flipud(original_array) 
print('Reverse an Array is  ',reverse_array)

Orginal Array is   [1 2 3 4 5 6 7 8 9]
Reverse an Array is   [9 8 7 6 5 4 3 2 1]
Reverse an Array is   [9 8 7 6 5 4 3 2 1]


In [100]:
#3. Write a Python program to create a 3x3 matrix with values ranging from 0 to 8

import numpy as np

result_array = np.arange(9).reshape(3,3)
print('Result a 3x3 matrix with values ranging from 0 to 8  \n',result_array)


Result a 3x3 matrix with values ranging from 0 to 8  
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [102]:
#4. Write a Python program to find indices of non-zero elements from [1,2,0,0,4,0]
result_indicies_non_zero =np.nonzero([1,2,0,0,4,0])[0]
print('indices of non-zero elements from [1,2,0,0,4,0] are',result_indicies_non_zero)

indices of non-zero elements from [1,2,0,0,4,0] are [0 1 4]


In [28]:
#5. Write a Python program to create a 3x3x3 array with random values
import numpy as np

result_3_3_3_array = np.random.random((3,3,3))
print('create a 3x3x3 array with random values are  ',result_3_3_3_array)

create a 3x3x3 array with random values are   [[[0.89811828 0.5785151  0.54818869]
  [0.66544616 0.07561108 0.06692776]
  [0.14125375 0.87317997 0.15028601]]

 [[0.75175983 0.98284842 0.72868184]
  [0.40719722 0.38611501 0.4379061 ]
  [0.3809385  0.41032497 0.771193  ]]

 [[0.08934393 0.10650187 0.23681309]
  [0.86448149 0.80390288 0.59921068]
  [0.16701911 0.37412954 0.78203155]]]


In [34]:
#6. Write a Python program to create a 10x10 array with random values and find the minimum and maximum values

import numpy as np
random_10_10_values = np.arange(0,100).reshape(10,10)
print('minimum_values = ',random_10_10_values.min())
print('maximum_values = ',random_10_10_values.max())

minimum_values =  0
maximum_values =  99


In [84]:
#7. Write a Python program to create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
nit_array = np.random.randint(5, size=(5,5))
print()
print('5x5 matrix with row values ranging from 0 to 4 ',init_array)


5x5 matrix with row values ranging from 0 to 4  [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [66]:
#8. Write a Python program to find the nearest value from a given value in an array.
input_array= np.random.random(10)
print('value from a given value in an array is ',input_array)
nearest_avlue=0.5
expected_array = input_array.flat[np.abs(input_array - nearest_avlue).argmin()]
print(' nearest value from a given value in an array is ',expected_array)

value from a given value in an array is  [0.22045202 0.876866   0.39500541 0.10532684 0.14971324 0.26801324
 0.1650745  0.70316628 0.73759493 0.51335174]
 nearest value from a given value in an array is  0.5133517410853545


In [85]:
#9. Write a Python program to find whether two random arrays A and B are equal
first_array = np.random.random(6)
second_array = np.random.random(6)
print('random arrays A is ',first_array)
print()
print('random arrays B is ',second_array)
array_equal = np.allclose(first_array, second_array)
print()
if array_equal == True:
    print(' two random arrays A and B are  equal')
else:
    print('two random arrays A and B are not equal')

random arrays A is  [0.10390868 0.91828522 0.13813035 0.9627789  0.13009544 0.53612723]

random arrays B is  [0.56200584 0.24569952 0.21589953 0.89632671 0.07964494 0.12441503]

two random arrays A and B are not equal


In [90]:
#9. Write a Python program to find whether two random arrays A and B are equal
first_array=np.random.random((3,3))

second_array=np.random.random((3,3))
array_equal=np.array_equal(first_array,second_array)
print(first_array)
print()
print(second_array)
print()
if array_equal == True:
    print(' two random arrays A and B are  equal')
else:
    print('two random arrays A and B are not equal')


[[0.12186917 0.66997441 0.30332363]
 [0.95546947 0.54778243 0.70771717]
 [0.98349209 0.01914308 0.76137711]]

[[0.83371597 0.49260246 0.67238855]
 [0.54905928 0.25544037 0.29245207]
 [0.03801608 0.04643667 0.5065697 ]]

two random arrays A and B are not equal


10. Consider the vector [1, 2, 3, 4, 5], write a Python program to build a new vector with three consecutive zeros interleaved between each value.


In [95]:
#10. Consider the vector [1, 2, 3, 4, 5], 
#write a Python program to build a new vector with three consecutive zeros interleaved between each value
init_vector =np.array([1, 2, 3, 4, 5],dtype =int)
zeros_array=np.zeros(20)

zeros_array[::4] = init_vector
print(zeros_array)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]
